---
- name: Create a new Demo EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-00399ec92321828f5  # Ubuntu 20.04 LTS
      keypair: bsr # peim file name
      subnetid: subnet-1947a271
      group: sg-0738506f

  tasks:

    - name: Create an ec2 instance
      ec2:
         aws_access_key: xxxxxxxxx  # AWS access_key here
         aws_secret_key: xxxxxxxx   # AWS secret_key here
         key_name: "{{ keypair }}"
         group_id: "{{ group }}"  #security group name
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: ec2_launch_by_ansible
         instance_tags:
            Name: ec2_launch_by_ansible
         vpc_subnet_id: "{{ subnetid }}"
         assign_public_ip: yes
      register: ec2
